// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WriteMe.Data;

namespace WriteMe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201006160032_AddedImagesMessages")]
    partial class AddedImagesMessages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "a9ae4eb3-b118-4dbc-9207-c1486f4f85c7",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "81c68196-fc65-480b-83a5-f3ecbf3fcb00",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WriteMe.Data.Entities.Chat", b =>
                {
                    b.Property<int>("ChatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendListId")
                        .HasColumnType("int");

                    b.HasKey("ChatId");

                    b.HasIndex("FriendListId")
                        .IsUnique();

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            ChatId = 1,
                            FriendListId = 1
                        },
                        new
                        {
                            ChatId = 2,
                            FriendListId = 2
                        },
                        new
                        {
                            ChatId = 3,
                            FriendListId = 3
                        },
                        new
                        {
                            ChatId = 4,
                            FriendListId = 4
                        });
                });

            modelBuilder.Entity("WriteMe.Data.Entities.FriendList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FriendsRelationshipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FriendsRelationshipId");

                    b.ToTable("FriendLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FriendsRelationshipId = 1
                        },
                        new
                        {
                            Id = 2,
                            FriendsRelationshipId = 1
                        },
                        new
                        {
                            Id = 3,
                            FriendsRelationshipId = 1
                        },
                        new
                        {
                            Id = 4,
                            FriendsRelationshipId = 2
                        });
                });

            modelBuilder.Entity("WriteMe.Data.Entities.FriendListUser", b =>
                {
                    b.Property<int>("FriendListId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FriendListId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FriendListUsers");

                    b.HasData(
                        new
                        {
                            FriendListId = 1,
                            UserId = 1
                        },
                        new
                        {
                            FriendListId = 1,
                            UserId = 2
                        },
                        new
                        {
                            FriendListId = 2,
                            UserId = 3
                        },
                        new
                        {
                            FriendListId = 2,
                            UserId = 4
                        },
                        new
                        {
                            FriendListId = 3,
                            UserId = 3
                        },
                        new
                        {
                            FriendListId = 3,
                            UserId = 2
                        },
                        new
                        {
                            FriendListId = 4,
                            UserId = 3
                        },
                        new
                        {
                            FriendListId = 4,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("WriteMe.Data.Entities.FriendsRelationship", b =>
                {
                    b.Property<int>("FriendsRelationshipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FriendsRelationshipId");

                    b.ToTable("FriendsRelationships");

                    b.HasData(
                        new
                        {
                            FriendsRelationshipId = 1,
                            Name = "Friend"
                        },
                        new
                        {
                            FriendsRelationshipId = 2,
                            Name = "Blocked"
                        });
                });

            modelBuilder.Entity("WriteMe.Data.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsImage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("bit");

                    b.Property<int>("RelatedUserId")
                        .HasColumnType("int");

                    b.Property<int>("RelatingUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SendingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.HasIndex("RelatedUserId");

                    b.HasIndex("RelatingUserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            MessageId = 1,
                            ChatId = 1,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 1,
                            RelatingUserId = 2,
                            SendingTime = new DateTime(2020, 10, 5, 22, 0, 0, 0, DateTimeKind.Local),
                            Text = "Hello, Vika"
                        },
                        new
                        {
                            MessageId = 2,
                            ChatId = 1,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 2,
                            RelatingUserId = 1,
                            SendingTime = new DateTime(2020, 10, 5, 22, 10, 0, 0, DateTimeKind.Local),
                            Text = "Hello, Julie"
                        },
                        new
                        {
                            MessageId = 3,
                            ChatId = 2,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 3,
                            RelatingUserId = 4,
                            SendingTime = new DateTime(2020, 10, 5, 22, 0, 0, 0, DateTimeKind.Local),
                            Text = "Hello, dimon"
                        },
                        new
                        {
                            MessageId = 4,
                            ChatId = 2,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 4,
                            RelatingUserId = 3,
                            SendingTime = new DateTime(2020, 10, 5, 22, 10, 0, 0, DateTimeKind.Local),
                            Text = "Hello, admin"
                        },
                        new
                        {
                            MessageId = 5,
                            ChatId = 3,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 2,
                            RelatingUserId = 3,
                            SendingTime = new DateTime(2020, 10, 5, 22, 0, 0, 0, DateTimeKind.Local),
                            Text = "Hello, admin"
                        },
                        new
                        {
                            MessageId = 6,
                            ChatId = 3,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 3,
                            RelatingUserId = 2,
                            SendingTime = new DateTime(2020, 10, 5, 22, 10, 0, 0, DateTimeKind.Local),
                            Text = "Hello, Vika"
                        },
                        new
                        {
                            MessageId = 7,
                            ChatId = 4,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 1,
                            RelatingUserId = 3,
                            SendingTime = new DateTime(2020, 10, 5, 22, 0, 0, 0, DateTimeKind.Local),
                            Text = "Hello, admin"
                        },
                        new
                        {
                            MessageId = 8,
                            ChatId = 4,
                            IsImage = false,
                            IsVideo = false,
                            RelatedUserId = 3,
                            RelatingUserId = 1,
                            SendingTime = new DateTime(2020, 10, 5, 22, 10, 0, 0, DateTimeKind.Local),
                            Text = "Hello, julie. Idi v ban"
                        });
                });

            modelBuilder.Entity("WriteMe.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "93072fee-fd15-49bf-bcb6-5a50976455a3",
                            Email = "jylie@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JYLIE@GMAIL.COM",
                            NormalizedUserName = "JYLIE@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMX354zwZC5PhmyVdWxlp5EbdsJJv8Tsi3ucQR8G6uHWvGSS+xSOC+Tf3RIM1Gb1fQ==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "304042a2-29bd-410c-8097-1744461b6c88_I2ff7ApwdMAM.jpg",
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "jylie@mail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "47e2dadf-a8f0-4828-9147-3e24039dd25e",
                            Email = "vika@mail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "VIKA@GMAIL.COM",
                            NormalizedUserName = "VIKA@MAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELP7/6X9RFIcFZmcJLJTsXJ1JhYbuydzXqgnsDlf8tASIInDprx92wKqQNnB1EIVkA==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "304042a2-29bd-410c-8097-1744461b6c88_photo_2019-01-26_19-32-55.jpg",
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "vika@mail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8343de29-b637-4276-81ed-c94b0a76988a",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELo5iERV+aHawiTwAiLWDlc2LiMYfvpcxNdGiFmegohMVSGp3tkQq+AVKn3xwuj6kw==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "304042a2-29bd-410c-8097-1744461b6c88_photo_2020-03-28_22-57-55.jpg",
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2f9137ea-e43e-4862-b34d-621e62a52c5b",
                            Email = "iwannaexplore@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "IWANNAEXPLORE@GMAIL.COM",
                            NormalizedUserName = "IWANNAEXPLORE@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAECJSqFue0LqR0UGVUv0Ah/B4OEMAnkQN+sITHHYzHMmdywck+/CYohZ6NIz7C/JWyg==",
                            PhoneNumberConfirmed = false,
                            ProfilePicture = "304042a2-29bd-410c-8097-1744461b6c88_photo_2020-04-24_17-05-28.jpg",
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "iwannaexplore@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WriteMe.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WriteMe.Data.Entities.Chat", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.FriendList", "FriendList")
                        .WithOne("Chat")
                        .HasForeignKey("WriteMe.Data.Entities.Chat", "FriendListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WriteMe.Data.Entities.FriendList", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.FriendsRelationship", "FriendsRelationship")
                        .WithMany()
                        .HasForeignKey("FriendsRelationshipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WriteMe.Data.Entities.FriendListUser", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.FriendList", "FriendList")
                        .WithMany("FriendListUsers")
                        .HasForeignKey("FriendListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WriteMe.Data.Entities.User", "User")
                        .WithMany("FriendListUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WriteMe.Data.Entities.Message", b =>
                {
                    b.HasOne("WriteMe.Data.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WriteMe.Data.Entities.User", "RelatedUser")
                        .WithMany("RelatedMessage")
                        .HasForeignKey("RelatedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WriteMe.Data.Entities.User", "RelatingUser")
                        .WithMany("RelatingMessages")
                        .HasForeignKey("RelatingUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
